//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapeOpen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class unitCategories_xml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal unitCategories_xml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapeOpen.Resources.unitCategories.xml", typeof(unitCategories_xml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CategorySpecifications&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Mass&lt;/Category&gt;
        ///    &lt;Aspen&gt;MASS&lt;/Aspen&gt;
        ///    &lt;SI_Unit&gt;kg&lt;/SI_Unit&gt;
        ///    &lt;Mass&gt;1&lt;/Mass&gt;
        ///    &lt;Time&gt;0&lt;/Time&gt;
        ///    &lt;Length&gt;0&lt;/Length&gt;
        ///    &lt;ElectricalCurrent&gt;0&lt;/ElectricalCurrent&gt;
        ///    &lt;Temperature&gt;0&lt;/Temperature&gt;
        ///    &lt;AmountOfSubstance&gt;0&lt;/AmountOfSubstance&gt;
        ///    &lt;Luminous&gt;0&lt;/Luminous&gt;
        ///    &lt;Currency&gt;0&lt;/Currency&gt;
        ///    &lt;Comment&gt;
        ///    &lt;/Comment&gt;
        ///  &lt;/Category_Spec&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Time&lt;/Category [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unitCategories {
            get {
                return ResourceManager.GetString("unitCategories", resourceCulture);
            }
        }
    }
}
