//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapeOpen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WARdata_xml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WARdata_xml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapeOpen.Resources.WARdata.xml", typeof(WARdata_xml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;dataroot xmlns:od=&quot;urn:schemas-microsoft-com:officedata&quot; generated=&quot;2008-09-23T14:52:13&quot;&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;THERMINOL 55&lt;/ChemicalName&gt;
        ///&lt;CAS&gt; 68855-24-3&lt;/CAS&gt;
        ///&lt;Rat_LD50_Value&gt;3500&lt;/Rat_LD50_Value&gt;
        ///&lt;Rat_LD50_Notes&gt;est&lt;/Rat_LD50_Notes&gt;
        ///&lt;Rat_LD50_Source&gt;C&lt;/Rat_LD50_Source&gt;
        ///&lt;OSHA_TWA_Notes&gt;N&lt;/OSHA_TWA_Notes&gt;
        ///&lt;FHM_LC50_Value&gt;171&lt;/FHM_LC50_Value&gt;
        ///&lt;FHM_LC50_Notes&gt;est - ave&lt;/FHM_LC50_Notes&gt;
        ///&lt;FHM_LC50_Source&gt;Q&lt;/FHM_LC50_Source&gt;
        ///&lt;/data&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;CAL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WARdata {
            get {
                return ResourceManager.GetString("WARdata", resourceCulture);
            }
        }
    }
}
