//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapeOpen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapeOpen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon epa_seal_medium {
            get {
                object obj = ResourceManager.GetObject("epa_seal_medium", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CategorySpecifications&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Mass&lt;/Category&gt;
        ///    &lt;Aspen&gt;MASS&lt;/Aspen&gt;
        ///    &lt;SI_Unit&gt;kg&lt;/SI_Unit&gt;
        ///    &lt;Mass&gt;1&lt;/Mass&gt;
        ///    &lt;Time&gt;0&lt;/Time&gt;
        ///    &lt;Length&gt;0&lt;/Length&gt;
        ///    &lt;ElectricalCurrent&gt;0&lt;/ElectricalCurrent&gt;
        ///    &lt;Temperature&gt;0&lt;/Temperature&gt;
        ///    &lt;AmountOfSubstance&gt;0&lt;/AmountOfSubstance&gt;
        ///    &lt;Luminous&gt;0&lt;/Luminous&gt;
        ///    &lt;Currency&gt;0&lt;/Currency&gt;
        ///    &lt;Comment&gt;
        ///    &lt;/Comment&gt;
        ///  &lt;/Category_Spec&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Time&lt;/Category [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unitCategories {
            get {
                return ResourceManager.GetString("unitCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Units&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;mol&lt;/Unit&gt;
        ///    &lt;Category&gt;AmountOfSubstance&lt;/Category&gt;
        ///    &lt;ConversionTimes&gt;1&lt;/ConversionTimes&gt;
        ///    &lt;ConversionPlus&gt;0&lt;/ConversionPlus&gt;
        ///    &lt;Comments&gt;0&lt;/Comments&gt;
        ///  &lt;/Unit_Specs&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;US$&lt;/Unit&gt;
        ///    &lt;Category&gt;Currency&lt;/Category&gt;
        ///    &lt;ConversionTimes&gt;1&lt;/ConversionTimes&gt;
        ///    &lt;ConversionPlus&gt;0&lt;/ConversionPlus&gt;
        ///    &lt;Comments&gt;0&lt;/Comments&gt;
        ///  &lt;/Unit_Specs&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;A/cm2&lt;/Unit&gt;
        ///    &lt;Category&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;dataroot xmlns:od=&quot;urn:schemas-microsoft-com:officedata&quot; generated=&quot;2008-09-23T14:52:13&quot;&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;THERMINOL 55&lt;/ChemicalName&gt;
        ///&lt;CAS&gt; 68855-24-3&lt;/CAS&gt;
        ///&lt;Rat_LD50_Value&gt;3500&lt;/Rat_LD50_Value&gt;
        ///&lt;Rat_LD50_Notes&gt;est&lt;/Rat_LD50_Notes&gt;
        ///&lt;Rat_LD50_Source&gt;C&lt;/Rat_LD50_Source&gt;
        ///&lt;OSHA_TWA_Notes&gt;N&lt;/OSHA_TWA_Notes&gt;
        ///&lt;FHM_LC50_Value&gt;171&lt;/FHM_LC50_Value&gt;
        ///&lt;FHM_LC50_Notes&gt;est - ave&lt;/FHM_LC50_Notes&gt;
        ///&lt;FHM_LC50_Source&gt;Q&lt;/FHM_LC50_Source&gt;
        ///&lt;/data&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;CAL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WARdata {
            get {
                return ResourceManager.GetString("WARdata", resourceCulture);
            }
        }
    }
}
